services:
  api:
    build: .
    ports:
      - "${APP_PORT}:3000"
    networks:
      - publica
      - privada
    depends_on:
      cache:
        condition: service_healthy
    restart: on-failure
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  cache:
    image: redis:7.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes
    volumes:
      - datos-redis:/data
    networks:
      - privada

volumes:
  datos-redis:

networks:
  publica:
  privada: