# builder
FROM python:3.12-slim as builder

WORKDIR /app

COPY app.py .

RUN pip install --no-cache-dir flask

# final
FROM python:3.12-alpine3.23

RUN addgroup -S pyappgroup && adduser -S pyappuser -G pyappgroup

WORKDIR /app

COPY --from=builder /app/app.py .

RUN pip install --no-cache-dir flask

RUN chown -R pyappuser:pyappgroup /app

USER pyappuser

EXPOSE 5000

CMD ["python", "app.py"]